//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAppForm.BankAppTransactionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankAppTransactionService.TransactionWebServiceSoap")]
    public interface TransactionWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Deposit", ReplyAction="*")]
        bool Deposit(int senderId, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Deposit", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DepositAsync(int senderId, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Withdraw", ReplyAction="*")]
        bool Withdraw(int senderId, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Withdraw", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> WithdrawAsync(int senderId, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Transfer", ReplyAction="*")]
        bool Transfer(int senderId, int receiverId, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Transfer", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> TransferAsync(int senderId, int receiverId, decimal amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransactionWebServiceSoapChannel : BankAppForm.BankAppTransactionService.TransactionWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionWebServiceSoapClient : System.ServiceModel.ClientBase<BankAppForm.BankAppTransactionService.TransactionWebServiceSoap>, BankAppForm.BankAppTransactionService.TransactionWebServiceSoap {
        
        public TransactionWebServiceSoapClient() {
        }
        
        public TransactionWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Deposit(int senderId, decimal amount) {
            return base.Channel.Deposit(senderId, amount);
        }
        
        public System.Threading.Tasks.Task<bool> DepositAsync(int senderId, decimal amount) {
            return base.Channel.DepositAsync(senderId, amount);
        }
        
        public bool Withdraw(int senderId, decimal amount) {
            return base.Channel.Withdraw(senderId, amount);
        }
        
        public System.Threading.Tasks.Task<bool> WithdrawAsync(int senderId, decimal amount) {
            return base.Channel.WithdrawAsync(senderId, amount);
        }
        
        public bool Transfer(int senderId, int receiverId, decimal amount) {
            return base.Channel.Transfer(senderId, receiverId, amount);
        }
        
        public System.Threading.Tasks.Task<bool> TransferAsync(int senderId, int receiverId, decimal amount) {
            return base.Channel.TransferAsync(senderId, receiverId, amount);
        }
    }
}
