//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAppForm.Soap.BankAppCustomerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customers", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPasskeyField;
        
        private decimal BalanceField;
        
        private byte BalanceTypeField;
        
        private bool isActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BankAppForm.Soap.BankAppCustomerService.Transactions[] TransactionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerSurname {
            get {
                return this.CustomerSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerSurnameField, value) != true)) {
                    this.CustomerSurnameField = value;
                    this.RaisePropertyChanged("CustomerSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CustomerPasskey {
            get {
                return this.CustomerPasskeyField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPasskeyField, value) != true)) {
                    this.CustomerPasskeyField = value;
                    this.RaisePropertyChanged("CustomerPasskey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public byte BalanceType {
            get {
                return this.BalanceTypeField;
            }
            set {
                if ((this.BalanceTypeField.Equals(value) != true)) {
                    this.BalanceTypeField = value;
                    this.RaisePropertyChanged("BalanceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool isActive {
            get {
                return this.isActiveField;
            }
            set {
                if ((this.isActiveField.Equals(value) != true)) {
                    this.isActiveField = value;
                    this.RaisePropertyChanged("isActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public BankAppForm.Soap.BankAppCustomerService.Transactions[] Transactions {
            get {
                return this.TransactionsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionsField, value) != true)) {
                    this.TransactionsField = value;
                    this.RaisePropertyChanged("Transactions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transactions", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Transactions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TransactionIDField;
        
        private decimal TransactionAmountField;
        
        private int TransactorAccountNumberField;
        
        private System.Nullable<int> ReceiverAccountNumberField;
        
        private System.DateTime TransactionDateField;
        
        private bool isSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BankAppForm.Soap.BankAppCustomerService.Customers CustomerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TransactionID {
            get {
                return this.TransactionIDField;
            }
            set {
                if ((this.TransactionIDField.Equals(value) != true)) {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public decimal TransactionAmount {
            get {
                return this.TransactionAmountField;
            }
            set {
                if ((this.TransactionAmountField.Equals(value) != true)) {
                    this.TransactionAmountField = value;
                    this.RaisePropertyChanged("TransactionAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int TransactorAccountNumber {
            get {
                return this.TransactorAccountNumberField;
            }
            set {
                if ((this.TransactorAccountNumberField.Equals(value) != true)) {
                    this.TransactorAccountNumberField = value;
                    this.RaisePropertyChanged("TransactorAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> ReceiverAccountNumber {
            get {
                return this.ReceiverAccountNumberField;
            }
            set {
                if ((this.ReceiverAccountNumberField.Equals(value) != true)) {
                    this.ReceiverAccountNumberField = value;
                    this.RaisePropertyChanged("ReceiverAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime TransactionDate {
            get {
                return this.TransactionDateField;
            }
            set {
                if ((this.TransactionDateField.Equals(value) != true)) {
                    this.TransactionDateField = value;
                    this.RaisePropertyChanged("TransactionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool isSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                if ((this.isSuccessField.Equals(value) != true)) {
                    this.isSuccessField = value;
                    this.RaisePropertyChanged("isSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public BankAppForm.Soap.BankAppCustomerService.Customers Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankAppCustomerService.CustomerWebServiceSoap")]
    public interface CustomerWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCustomer", ReplyAction="*")]
        BankAppForm.Soap.BankAppCustomerService.InsertCustomerResponse InsertCustomer(BankAppForm.Soap.BankAppCustomerService.InsertCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<BankAppForm.Soap.BankAppCustomerService.InsertCustomerResponse> InsertCustomerAsync(BankAppForm.Soap.BankAppCustomerService.InsertCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomer", ReplyAction="*")]
        BankAppForm.Soap.BankAppCustomerService.UpdateCustomerResponse UpdateCustomer(BankAppForm.Soap.BankAppCustomerService.UpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<BankAppForm.Soap.BankAppCustomerService.UpdateCustomerResponse> UpdateCustomerAsync(BankAppForm.Soap.BankAppCustomerService.UpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCustomer", ReplyAction="*")]
        bool DeleteCustomer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteCustomerAsync(int id);
        
        // CODEGEN: Generating message contract since element name SelectAllCustomersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllCustomers", ReplyAction="*")]
        BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersResponse SelectAllCustomers(BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllCustomers", ReplyAction="*")]
        System.Threading.Tasks.Task<BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersResponse> SelectAllCustomersAsync(BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersRequest request);
        
        // CODEGEN: Generating message contract since element name SelectCustomerByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectCustomerById", ReplyAction="*")]
        BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdResponse SelectCustomerById(BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectCustomerById", ReplyAction="*")]
        System.Threading.Tasks.Task<BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdResponse> SelectCustomerByIdAsync(BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCustomer", Namespace="http://tempuri.org/", Order=0)]
        public BankAppForm.Soap.BankAppCustomerService.InsertCustomerRequestBody Body;
        
        public InsertCustomerRequest() {
        }
        
        public InsertCustomerRequest(BankAppForm.Soap.BankAppCustomerService.InsertCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankAppForm.Soap.BankAppCustomerService.Customers entity;
        
        public InsertCustomerRequestBody() {
        }
        
        public InsertCustomerRequestBody(BankAppForm.Soap.BankAppCustomerService.Customers entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankAppForm.Soap.BankAppCustomerService.InsertCustomerResponseBody Body;
        
        public InsertCustomerResponse() {
        }
        
        public InsertCustomerResponse(BankAppForm.Soap.BankAppCustomerService.InsertCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertCustomerResult;
        
        public InsertCustomerResponseBody() {
        }
        
        public InsertCustomerResponseBody(bool InsertCustomerResult) {
            this.InsertCustomerResult = InsertCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomer", Namespace="http://tempuri.org/", Order=0)]
        public BankAppForm.Soap.BankAppCustomerService.UpdateCustomerRequestBody Body;
        
        public UpdateCustomerRequest() {
        }
        
        public UpdateCustomerRequest(BankAppForm.Soap.BankAppCustomerService.UpdateCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankAppForm.Soap.BankAppCustomerService.Customers entity;
        
        public UpdateCustomerRequestBody() {
        }
        
        public UpdateCustomerRequestBody(BankAppForm.Soap.BankAppCustomerService.Customers entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankAppForm.Soap.BankAppCustomerService.UpdateCustomerResponseBody Body;
        
        public UpdateCustomerResponse() {
        }
        
        public UpdateCustomerResponse(BankAppForm.Soap.BankAppCustomerService.UpdateCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateCustomerResult;
        
        public UpdateCustomerResponseBody() {
        }
        
        public UpdateCustomerResponseBody(bool UpdateCustomerResult) {
            this.UpdateCustomerResult = UpdateCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllCustomersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllCustomers", Namespace="http://tempuri.org/", Order=0)]
        public BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersRequestBody Body;
        
        public SelectAllCustomersRequest() {
        }
        
        public SelectAllCustomersRequest(BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectAllCustomersRequestBody {
        
        public SelectAllCustomersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllCustomersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllCustomersResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersResponseBody Body;
        
        public SelectAllCustomersResponse() {
        }
        
        public SelectAllCustomersResponse(BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAllCustomersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankAppForm.Soap.BankAppCustomerService.Customers[] SelectAllCustomersResult;
        
        public SelectAllCustomersResponseBody() {
        }
        
        public SelectAllCustomersResponseBody(BankAppForm.Soap.BankAppCustomerService.Customers[] SelectAllCustomersResult) {
            this.SelectAllCustomersResult = SelectAllCustomersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectCustomerByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectCustomerById", Namespace="http://tempuri.org/", Order=0)]
        public BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdRequestBody Body;
        
        public SelectCustomerByIdRequest() {
        }
        
        public SelectCustomerByIdRequest(BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectCustomerByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public SelectCustomerByIdRequestBody() {
        }
        
        public SelectCustomerByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectCustomerByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectCustomerByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdResponseBody Body;
        
        public SelectCustomerByIdResponse() {
        }
        
        public SelectCustomerByIdResponse(BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectCustomerByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankAppForm.Soap.BankAppCustomerService.Customers SelectCustomerByIdResult;
        
        public SelectCustomerByIdResponseBody() {
        }
        
        public SelectCustomerByIdResponseBody(BankAppForm.Soap.BankAppCustomerService.Customers SelectCustomerByIdResult) {
            this.SelectCustomerByIdResult = SelectCustomerByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerWebServiceSoapChannel : BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerWebServiceSoapClient : System.ServiceModel.ClientBase<BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap>, BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap {
        
        public CustomerWebServiceSoapClient() {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankAppForm.Soap.BankAppCustomerService.InsertCustomerResponse BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap.InsertCustomer(BankAppForm.Soap.BankAppCustomerService.InsertCustomerRequest request) {
            return base.Channel.InsertCustomer(request);
        }
        
        public bool InsertCustomer(BankAppForm.Soap.BankAppCustomerService.Customers entity) {
            BankAppForm.Soap.BankAppCustomerService.InsertCustomerRequest inValue = new BankAppForm.Soap.BankAppCustomerService.InsertCustomerRequest();
            inValue.Body = new BankAppForm.Soap.BankAppCustomerService.InsertCustomerRequestBody();
            inValue.Body.entity = entity;
            BankAppForm.Soap.BankAppCustomerService.InsertCustomerResponse retVal = ((BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap)(this)).InsertCustomer(inValue);
            return retVal.Body.InsertCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankAppForm.Soap.BankAppCustomerService.InsertCustomerResponse> BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap.InsertCustomerAsync(BankAppForm.Soap.BankAppCustomerService.InsertCustomerRequest request) {
            return base.Channel.InsertCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankAppForm.Soap.BankAppCustomerService.InsertCustomerResponse> InsertCustomerAsync(BankAppForm.Soap.BankAppCustomerService.Customers entity) {
            BankAppForm.Soap.BankAppCustomerService.InsertCustomerRequest inValue = new BankAppForm.Soap.BankAppCustomerService.InsertCustomerRequest();
            inValue.Body = new BankAppForm.Soap.BankAppCustomerService.InsertCustomerRequestBody();
            inValue.Body.entity = entity;
            return ((BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap)(this)).InsertCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankAppForm.Soap.BankAppCustomerService.UpdateCustomerResponse BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap.UpdateCustomer(BankAppForm.Soap.BankAppCustomerService.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomer(request);
        }
        
        public bool UpdateCustomer(BankAppForm.Soap.BankAppCustomerService.Customers entity) {
            BankAppForm.Soap.BankAppCustomerService.UpdateCustomerRequest inValue = new BankAppForm.Soap.BankAppCustomerService.UpdateCustomerRequest();
            inValue.Body = new BankAppForm.Soap.BankAppCustomerService.UpdateCustomerRequestBody();
            inValue.Body.entity = entity;
            BankAppForm.Soap.BankAppCustomerService.UpdateCustomerResponse retVal = ((BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap)(this)).UpdateCustomer(inValue);
            return retVal.Body.UpdateCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankAppForm.Soap.BankAppCustomerService.UpdateCustomerResponse> BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap.UpdateCustomerAsync(BankAppForm.Soap.BankAppCustomerService.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankAppForm.Soap.BankAppCustomerService.UpdateCustomerResponse> UpdateCustomerAsync(BankAppForm.Soap.BankAppCustomerService.Customers entity) {
            BankAppForm.Soap.BankAppCustomerService.UpdateCustomerRequest inValue = new BankAppForm.Soap.BankAppCustomerService.UpdateCustomerRequest();
            inValue.Body = new BankAppForm.Soap.BankAppCustomerService.UpdateCustomerRequestBody();
            inValue.Body.entity = entity;
            return ((BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap)(this)).UpdateCustomerAsync(inValue);
        }
        
        public bool DeleteCustomer(int id) {
            return base.Channel.DeleteCustomer(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCustomerAsync(int id) {
            return base.Channel.DeleteCustomerAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersResponse BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap.SelectAllCustomers(BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersRequest request) {
            return base.Channel.SelectAllCustomers(request);
        }
        
        public BankAppForm.Soap.BankAppCustomerService.Customers[] SelectAllCustomers() {
            BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersRequest inValue = new BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersRequest();
            inValue.Body = new BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersRequestBody();
            BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersResponse retVal = ((BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap)(this)).SelectAllCustomers(inValue);
            return retVal.Body.SelectAllCustomersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersResponse> BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap.SelectAllCustomersAsync(BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersRequest request) {
            return base.Channel.SelectAllCustomersAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersResponse> SelectAllCustomersAsync() {
            BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersRequest inValue = new BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersRequest();
            inValue.Body = new BankAppForm.Soap.BankAppCustomerService.SelectAllCustomersRequestBody();
            return ((BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap)(this)).SelectAllCustomersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdResponse BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap.SelectCustomerById(BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdRequest request) {
            return base.Channel.SelectCustomerById(request);
        }
        
        public BankAppForm.Soap.BankAppCustomerService.Customers SelectCustomerById(int id) {
            BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdRequest inValue = new BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdRequest();
            inValue.Body = new BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdRequestBody();
            inValue.Body.id = id;
            BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdResponse retVal = ((BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap)(this)).SelectCustomerById(inValue);
            return retVal.Body.SelectCustomerByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdResponse> BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap.SelectCustomerByIdAsync(BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdRequest request) {
            return base.Channel.SelectCustomerByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdResponse> SelectCustomerByIdAsync(int id) {
            BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdRequest inValue = new BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdRequest();
            inValue.Body = new BankAppForm.Soap.BankAppCustomerService.SelectCustomerByIdRequestBody();
            inValue.Body.id = id;
            return ((BankAppForm.Soap.BankAppCustomerService.CustomerWebServiceSoap)(this)).SelectCustomerByIdAsync(inValue);
        }
    }
}
